#Несбалансированная классификация: выявление случаев мошенничества с кредитными картами

## Introduction

This example looks at the
[Kaggle Credit Card Fraud Detection](https://www.kaggle.com/mlg-ulb/creditcardfraud/)
dataset to demonstrate how
to train a classification model on data with highly imbalanced classes.

In [1]:
# импортируем основные библиотеки
import numpy as np
import pandas as pd

#Загрузим наши данные

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

print("Path to dataset files:", path)

100%|██████████| 66.0M/66.0M [00:00<00:00, 133MB/s]

Extracting files...


Path to dataset files: /root/.cache/kagglehub/datasets/mlg-ulb/creditcardfraud/versions/3


In [3]:
!wget 'https://www.kaggle.com/api/v1/datasets/download/mlg-ulb/creditcardfraud?dataset_version_number=3'

--2024-12-07 12:35:32--  https://www.kaggle.com/api/v1/datasets/download/mlg-ulb/creditcardfraud?dataset_version_number=3
Resolving www.kaggle.com (www.kaggle.com)... 35.244.233.98
Connecting to www.kaggle.com (www.kaggle.com)|35.244.233.98|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com:443/kaggle-data-sets/310/23498/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20241207%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20241207T123532Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=72d44d5e61b0adfd289538b7fc8e22be8587f8ef56b173294338808b554c4944017485a3c242cee7c08c4f9f729131ce1de046da25a67418654e415c6448e0e44d63debbb9f4bccdd0dc81c0c6f83b448f217346c9c6db07b803fff5b4cb343b9c1c52e0d03023e7d426a18bbb66504a63e83d7a8d23932e10e80d36bb6b5eb53a8b54ebf43255c973058d569d6d99b6ea18130bf063fa569798023ccfd4db75481717e26c4912638fc269a41ed255a38f

In [4]:
import zipfile

# Путь к zip-архиву
archive_path = '/content/creditcardfraud?dataset_version_number=3'

# Распаковываем zip-архив
with zipfile.ZipFile(archive_path, 'r') as zip_ref:
    zip_ref.extractall()

In [5]:
# загружаю датасет
path_file = '/content/creditcard.csv'
# загружаю данные
df = pd.read_csv(path_file)
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [6]:
# проверим на пропуски
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [Time, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11, V12, V13, V14, V15, V16, V17, V18, V19, V20, V21, V22, V23, V24, V25, V26, V27, V28, Amount, Class]
Index: []

[0 rows x 31 columns]

In [7]:
# проверим на пропуски
df.isna().sum().sum()

0

#Подготовим набор для обучения

In [8]:
# подготовим данные для обучения
from sklearn.model_selection import train_test_split

X = df.drop(columns='Class', axis=1)
y = df['Class']
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2, random_state=42
                                                    )

In [9]:
print(f'Number of training samples: {X_train.shape[0]+1}')
print(f'Number of validation samples: {X_test.shape[0]+1}')

Number of training samples: 227846
Number of validation samples: 56963


In [24]:
train_features = X_train.values
train_features

array([[ 1.43352000e+05,  1.95504092e+00, -3.80782711e-01, ...,
         4.51682478e-02, -4.71447917e-02,  9.99000000e+00],
       [ 1.17173000e+05, -4.00975239e-01, -6.26942769e-01, ...,
        -3.70468822e-01, -1.44791686e-01,  4.59000000e+01],
       [ 1.49565000e+05,  7.25090164e-02,  8.20565650e-01, ...,
         2.06394866e-01,  7.02877702e-02,  1.19900000e+01],
       ...,
       [ 7.97950000e+04, -1.46608925e-01,  9.92946123e-01, ...,
        -1.21139194e-01, -1.96195328e-01,  3.94000000e+00],
       [ 8.79310000e+04, -2.94863809e+00,  2.35484929e+00, ...,
         4.96912107e-01,  3.35821632e-01,  1.00000000e+00],
       [ 7.63810000e+04,  1.23317435e+00, -7.84850501e-01, ...,
         1.21657270e-03,  3.85878912e-02,  1.13000000e+02]])

In [25]:
val_features = X_test.values
val_features

array([[ 4.15050000e+04, -1.65265066e+01,  8.58497180e+00, ...,
        -2.01857525e+00, -1.04280417e+00,  3.64190000e+02],
       [ 4.42610000e+04,  3.39812064e-01, -2.74374524e+00, ...,
         4.09958027e-02,  1.02037825e-01,  5.20120000e+02],
       [ 3.54840000e+04,  1.39959027e+00, -5.90701288e-01, ...,
         1.14086454e-02,  4.63414166e-03,  3.10000000e+01],
       ...,
       [ 1.42491000e+05,  4.04414982e-02, -1.09736789e-01, ...,
         3.57844730e-01,  3.54379443e-01,  7.63000000e+00],
       [ 5.91570000e+04, -4.95047586e-01,  9.91480934e-01, ...,
         4.05292111e-02, -2.69775457e-01,  3.59000000e+00],
       [ 4.88640000e+04, -1.59048567e+00,  9.92415466e-01, ...,
         1.25749856e-01, -6.07225509e-01,  9.06310000e+02]])

#Проведем анализ дисбаланса в целевых группах

In [10]:
counts = np.bincount(y_train)
counts[0]

227451

In [11]:
y_train.shape[0]

227845

In [12]:
# посмотрим на соотношение проложительных и отрицательных транзакций
counts = np.bincount(y_train)
print(f'Всего транзакций: {y_train.shape[0]}. Из них:')
print(f'Реальных: {counts[0]}. Мошеннических: {counts[1]}, ({(counts[1]/counts[0])*100 :0.2f}%)')

weight_for_0 = 1.0 / counts[0]
weight_for_1 = 1.0 / counts[1]

Всего транзакций: 227845. Из них:
Реальных: 227451. Мошеннических: 394, (0.17%)


In [13]:
# настроим веса для балансировки модели
weight_for_0 = 1.0 / counts[0]
weight_for_1 = 1.0 / counts[1]
print(f'weight_for_0={weight_for_0}, weight_for_1 ={weight_for_1}')
print(f'справочно: weight_for_1/weight_for_0= {weight_for_1/weight_for_0 :0.2f}')

weight_for_0=4.396551345124884e-06, weight_for_1 =0.0025380710659898475
справочно: weight_for_1/weight_for_0= 577.29


#Нормализуем данные и проверим нормализацию

In [14]:
# данные ло нормализации
X_train.head()

Time        V1        V2        V3        V4        V5        V6  \
223361  143352.0  1.955041 -0.380783 -0.315013  0.330155 -0.509374 -0.086197   
165061  117173.0 -0.400975 -0.626943  1.555339 -2.017772 -0.107769  0.168310   
238186  149565.0  0.072509  0.820566 -0.561351 -0.709897  1.080399 -0.359429   
150562   93670.0 -0.535045  1.014587  1.750679  2.769390  0.500089  1.002270   
138452   82655.0 -4.026938  1.897371 -0.429786 -0.029571 -0.855751 -0.480406   

              V7        V8        V9  ...       V20       V21       V22  \
223361 -0.627978  0.035994  1.054560  ... -0.125390  0.238197  0.968305   
165061  0.017959 -0.401619  0.040378  ... -0.470372 -0.153485  0.421703   
238186  0.787858  0.117276 -0.131275  ...  0.012227 -0.314638 -0.872959   
150562  0.847902 -0.081323  0.371579  ... -0.253757  0.063525  0.443431   
138452 -0.435632  1.313760  0.536044  ... -0.012320 -0.480691 -0.230369   

             V23       V24       V25       V26       V27       V28  Amount  
223361  0.053208 -0.278602 -0.044999 -0.216780  0.045168 -0.047145    9.99  
165061  0.113442 -1.004095 -1.176695  0.361924 -0.370469 -0.144792   45.90  
238186  0.083391  0.148178 -0.431459  0.119690  0.206395  0.070288   11.99  
150562 -0.072754  0.448192 -0.655203 -0.181038 -0.093013 -0.064931  117.44  
138452  0.250717  0.066399  0.470787  0.245335  0.286904 -0.322672   25.76  

[5 rows x 30 columns]

In [26]:
mean = np.mean(train_features, axis=0)
train_features -= mean
val_features -= mean

std = np.std(train_features, axis=0)
train_features /= std
val_features /= std

In [17]:
# нормализуем
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_features = scaler.fit_transform(X_train)
val_features = scaler.fit_transform(X_test)
train_features[:3]

array([[ 1.02255459,  0.99785119, -0.22962626, -0.20738468,  0.23421529,
        -0.36779128, -0.0640219 , -0.50588871,  0.03060393,  0.95995457,
        -0.02686352,  0.61149957,  1.68999033,  1.26149805, -0.26397318,
        -0.36292946,  0.34942719, -1.09376318,  0.77802759,  0.20615616,
        -0.1625072 ,  0.32483903,  1.3366986 ,  0.08456891, -0.45980186,
        -0.08436785, -0.44894226,  0.11248883, -0.14374055, -0.30788875],
       [ 0.47128275, -0.205221  , -0.37821992,  1.02754428, -1.42410102,
        -0.07838016,  0.12636396,  0.01356656, -0.3375587 ,  0.03591349,
         0.56353152, -1.90538969, -0.72394599,  1.06569947, -1.24378077,
         0.69040336, -0.18326043, -1.91526546,  2.51448298, -2.07894444,
        -0.60819501, -0.2097972 ,  0.58308608,  0.18062005, -1.65808442,
        -2.25335207,  0.7505885 , -0.92189789, -0.43984143, -0.1670264 ],
       [ 1.15338663,  0.03655821,  0.49556347, -0.37003324, -0.50036261,
         0.77785588, -0.26841443,  0.63270968,  0

In [27]:
train_features[:3]

array([[ 1.02255459,  0.99785119, -0.22962626, -0.20738468,  0.23421529,
        -0.36779128, -0.0640219 , -0.50588871,  0.03060393,  0.95995457,
        -0.02686352,  0.61149957,  1.68999033,  1.26149805, -0.26397318,
        -0.36292946,  0.34942719, -1.09376318,  0.77802759,  0.20615616,
        -0.1625072 ,  0.32483903,  1.3366986 ,  0.08456891, -0.45980186,
        -0.08436785, -0.44894226,  0.11248883, -0.14374055, -0.30788875],
       [ 0.47128275, -0.205221  , -0.37821992,  1.02754428, -1.42410102,
        -0.07838016,  0.12636396,  0.01356656, -0.3375587 ,  0.03591349,
         0.56353152, -1.90538969, -0.72394599,  1.06569947, -1.24378077,
         0.69040336, -0.18326043, -1.91526546,  2.51448298, -2.07894444,
        -0.60819501, -0.2097972 ,  0.58308608,  0.18062005, -1.65808442,
        -2.25335207,  0.7505885 , -0.92189789, -0.43984143, -0.1670264 ],
       [ 1.15338663,  0.03655821,  0.49556347, -0.37003324, -0.50036261,
         0.77785588, -0.26841443,  0.63270968,  0

In [28]:
val_features[:3]

array([[-1.12211800e+00, -8.43953559e+00,  5.18252006e+00,
        -1.23132500e+01,  6.71473063e+00, -9.94103231e+00,
        -2.11833498e+00, -1.34321838e+01,  6.32464612e+00,
        -7.75182381e+00, -1.29838058e+01,  5.18902663e+00,
        -1.08139804e+01,  1.67873744e+00, -9.76999304e+00,
         3.94728463e-01, -1.12833432e+01, -2.25888621e+01,
        -1.00213793e+01,  3.80892357e+00, -1.95767041e+00,
         1.62503255e+00, -1.55306719e+00, -3.76135526e+00,
         1.11270028e+00, -2.70759003e+00, -9.58810527e-01,
        -5.02350367e+00, -3.16294175e+00,  1.08151380e+00],
       [-1.06408273e+00,  1.73053399e-01, -1.65602032e+00,
        -8.79140088e-02, -9.77696052e-01, -1.04665800e+00,
         7.60397307e-01, -4.22575724e-01,  1.88823961e-01,
         8.18900234e-01, -5.18804110e-01, -8.64208699e-02,
         9.79145681e-01,  7.71702924e-02, -2.27095291e-01,
        -1.49729204e-01, -2.44310412e+00,  1.48353899e-01,
         2.09181926e+00,  5.31046507e-01,  6.53253563e-

In [29]:
# проверим
train_features.mean(axis=0)

array([-6.33062720e-17,  1.22246594e-17, -2.18297490e-18,  1.42205222e-17,
        2.12060418e-18,  1.86488427e-17,  1.79315795e-17,  1.32537762e-18,
       -5.67573473e-18, -1.13514695e-17, -1.49689707e-18,  1.74637992e-17,
        7.48448536e-19,  1.65906092e-17,  8.10819247e-18, -1.33161469e-17,
       -4.98965690e-19, -7.09466841e-18, -5.23913975e-18,  1.15385816e-17,
       -5.73810544e-18, -1.33161469e-17,  7.98345105e-18,  5.36388117e-18,
        7.73396820e-18, -2.74431130e-18,  3.13724678e-17,  4.17883766e-18,
        3.43038912e-18,  3.64868661e-17])

In [30]:
train_features.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#Построим модель бинарной классификации

In [32]:
from tensorflow import keras

In [33]:
# построим модель
hid_size = 128
model = keras.Sequential(
    [
        keras.layers.Dense(hid_size, activation='relu', input_shape=(train_features.shape[1],)),
        keras.layers.Dense(hid_size*2, activation='relu'),
        keras.layers.Dropout(0.3),
        keras.layers.Dense(hid_size, activation='relu'),
        keras.layers.Dropout(0.3),
        keras.layers.Dense(1, activation='sigmoid')
    ]
)
model.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 128)                 │           3,968 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 256)                 │          33,024 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 256)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 70,017 (273.50 KB)

 Trainable params: 70,017 (273.50 KB)

 Non-trainable params: 0 (0.00 B)

#Обучим модель с `class_weight` аргументом

In [34]:
metrics = [
    keras.metrics.FalseNegatives(name='fn'),
    keras.metrics.FalsePositives(name='fp'),
    keras.metrics.TrueNegatives(name='tn'),
    keras.metrics.TruePositives(name='tp'),
    keras.metrics.Precision(name='precision'),
    keras.metrics.Recall(name='recall'),
]

model.compile(
    optimizer=keras.optimizers.Adam(1e-2), loss='binary_crossentropy', metrics=metrics
)

callbacks = [keras.callbacks.ModelCheckpoint('fraud_model_at_epoch_{epoch}.keras')]
class_weight = {0: weight_for_0, 1: weight_for_1}

model.fit(
    train_features,
    y_train.values,
    batch_size=2048,
    epochs=10,
    callbacks=callbacks,
    validation_data=(val_features, y_test.values),
    class_weight=class_weight,
)


Epoch 1/10
112/112 ━━━━━━━━━━━━━━━━━━━━ 8s 44ms/step - fn: 22.4336 - fp: 20170.5840 - loss: 3.7086e-06 - precision: 0.0080 - recall: 0.8683 - tn: 96323.2812 - tp: 174.4779 - val_fn: 5.0000 - val_fp: 9309.0000 - val_loss: 0.4536 - val_precision: 0.0099 - val_recall: 0.9490 - val_tn: 47555.0000 - val_tp: 93.0000
Epoch 2/10
112/112 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step - fn: 17.6991 - fp: 4924.2300 - loss: 1.5550e-06 - precision: 0.0318 - recall: 0.9107 - tn: 111569.7812 - tp: 179.0708 - val_fn: 9.0000 - val_fp: 1454.0000 - val_loss: 0.1258 - val_precision: 0.0577 - val_recall: 0.9082 - val_tn: 55410.0000 - val_tp: 89.0000
Epoch 3/10
112/112 ━━━━━━━━━━━━━━━━━━━━ 8s 36ms/step - fn: 15.8142 - fp: 3599.2478 - loss: 1.2854e-06 - precision: 0.0524 - recall: 0.9203 - tn: 112879.4141 - tp: 196.3009 - val_fn: 8.0000 - val_fp: 1149.0000 - val_loss: 0.0680 - val_precision: 0.0726 - val_recall: 0.9184 - val_tn: 55715.0000 - val_tp: 90.0000
Epoch 4/10
112/112 ━━━━━━━━━━━━━━━━━━━━ 9s 70ms/step - fn: 7.531